version: "3.9"

x-environment: &x-environment
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_NAME: ${POSTGRES_NAME}
  SECRET_KEY: ${SECRET_KEY}
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_PORT: ${POSTGRES_PORT}

volumes:
  postgres_data: {}

services:
  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      <<: *x-environment
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    
  web:
    build:
      context: .
      target: django-dev
      dockerfile: ./docker/Dockerfile
    environment:
      <<: *x-environment
    command: ["runserver", "0.0.0.0:8000"]
    depends_on: 
      - postgres
    volumes: 
      - .:/opt/app
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    