version: "3.9"

x-environment: &x-environment
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_PORT: ${POSTGRES_PORT}
  POSTGRES_HOST: ${POSTGRES_HOST}
  SECRET_KEY: ${SECRET_KEY}

volumes:
  postgres_data: {}

services:
  postgres:
    image: postgres:12-alpine
    environment:
      <<: *x-environment
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    
  web:
    build:
      context: .
      target: django-dev
      dockerfile: ./docker/Dockerfile
    environment:
      <<: *x-environment
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/opt/app
    depends_on: 
      - postgres
    ports:
      - "8000:8000"
    