# Generated by Django 3.1.5 on 2021-01-08 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210107_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='birthday_data',
            new_name='birthday_date',
        ),
    ]
