# Generated by Django 3.1.5 on 2021-01-10 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210108_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='birthday_date',
        ),
    ]
